name: CI - Build, Test, Coverage, Calidad y E2E

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Node.js dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Lint Next.js app
        run: npm run lint

      - name: Run frontend tests (Jest)
        run: |
          npm run test -- --coverage || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run backend tests (pytest)
        run: |
          pip install pytest
          pytest backend/tests --cov=backend || true

      - name: Subir cobertura a Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Instalar Playwright
        run: npx playwright install --with-deps

      - name: Ejecutar pruebas E2E
        run: npx playwright test || true

      - name: Subir screenshots de fallos
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: playwright-report/
