name: Python Backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
          pip install flake8 black pytest

      - name: Lint with flake8
        run: flake8 backend/

      - name: Check formatting with black
        run: black --check backend/

      - name: Run tests
        run: pytest backend/tests/

      - name: Check for unused or missing imports
        run: python backend/check_errors.py
        continue-on-error: true
